# Site settings
title: Robin Burton
email: 1.robinburton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
<<<<<<< HEAD
  Interventional Mammography Technologist and Apprentice Jr Software Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 1_robinburton 
=======
  Interventional Mammography Technologist and Apprentice Jr Software Developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 1_robinburton
>>>>>>> 1251d26f02e2835ee1aaeac2ce4dd85912b41465
github_username:  rob1nburt0n

# Build settings
markdown: kramdown
